# Generated by Django 4.2.22 on 2025-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('mac', models.TextField()),
                ('rx', models.BigIntegerField()),
                ('tx', models.BigIntegerField()),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_202506',
                'managed': False,
            },
        ),
    ]
