# Generated by Django 4.2.22 on 2025-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_macaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('mac', models.CharField(blank=True, max_length=17, null=True)),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('rx', models.BigIntegerField()),
                ('tx', models.BigIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='traffic',
            options={},
        ),
    ]
