# Generated by Django 4.2.22 on 2025-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_maccache_trafficbuffer_alter_traffic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maccache',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='traffic',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterModelTable(
            name='traffic',
            table='traffic',
        ),
        migrations.AlterModelTable(
            name='trafficbuffer',
            table='traffic_buffer',
        ),
    ]
