# Generated by Django 4.2.22 on 2025-06-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_alter_maccache_options_alter_traffic_inserted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traffic',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='maccache',
            table='mac_cache',
        ),
    ]
